import { compare, hash } from 'bcryptjs';

import type { Request, Response } from 'express';
import type { ValidationReturn } from '../lib/types.ts';

import { formValidation, generateUsername } from '../lib/utils.ts';
import { SignUpSchema, LogInSchema } from '../lib/schemas.ts';
import { getDb } from '../db.ts';

export async function signUpController(req: Request, res: Response): Promise<void> {

  // Validating data
  const validationResult = formValidation(SignUpSchema, req.body);

  // If validation failed
  if ('errors' in validationResult) {
    res.status(400).json(validationResult);
    return // finalize the function
  }

  // If validation went through
  const { email, password } = validationResult as ValidationReturn;

  // Getting the database instance
  let db = await getDb();
  if (!db) throw new Error(`Couldn't get database from multiplayer controller`);
  
  // Check if there is a user with the same email
  const duplicateEmail = await db.collection('users').findOne({ email: email });
  if (duplicateEmail) {
    res.status(400).json({ errors: ['This email is already being used'] });
    return // finalize the function
  }

  const hashedPassword = await hash(password, 10);
  
  const autoGeneratedUsername = generateUsername(email);

  // Adds brand new user to db
  await db
    .collection('users')
    .insertOne({
      username: autoGeneratedUsername,
      email: email,
      password: hashedPassword
    })

  res.status(200).json({ success: true });
  return; // finalize the function
}

export async function logInController(req: Request, res: Response): Promise<void> {
  const validationResult = formValidation(LogInSchema, req.body);

  // If validation failed
  if ('errors' in validationResult) {
    res.status(400).json(validationResult)
    return
  }

  // If validation went through
  const { email, password } = validationResult as ValidationReturn;

  // Getting the database instance
  const db = await getDb();
  if (!db) throw new Error(`Couldn't get database from multiplayer controller.`);

  const user = await db.collection('users').findOne({ email: email });

  if (!user) throw new Error(`Couldn't get user from database.`);

  const isValid = await compare(password, user.password);

  // Send a response back according to the password comparison
  isValid
    ? res.status(200).json({ success: true })
    : res.status(401).json({ errors: ['Invalid credentials'] }); // Copying how Zod returns errors

  return
}