import { hash } from 'bcryptjs';

import type { NextFunction, Request, Response } from 'express';
import type { ValidationReturn } from '../lib/types.ts';

import { formValidation, generateUsername } from '../lib/utils.ts';
import { SignUpSchema } from '../lib/schemas.ts';
import { getDb } from '../db.ts';

export async function signUpController(req: Request, res: Response): Promise<void> {

  // Validating data
  const validationResult = formValidation(SignUpSchema, req.body);

  // If validation failed
  if ('errors' in validationResult) {
    res.status(400).json(validationResult);
    return // finalize the function
  }

  // If validation went through
  const { email, password } = validationResult as ValidationReturn;

  // Getting the database instance
  let db = await getDb();
  if (!db) throw new Error(`Couldn't get database from multiplayer controller`);
  
  // Check if there is a user with the same email
  const duplicateEmail = await db.collection('users').findOne({ email: email });
  if (duplicateEmail) {
    res.status(400).json({ errors: ['This email is already being used'] });
    return // finalize the function
  }

  const hashedPassword = await hash(password, 10);
  
  const autoGeneratedUsername = generateUsername(email);

  // Adds brand new user to db
  await db
    .collection('users')
    .insertOne({
      username: autoGeneratedUsername,
      email: email,
      password: hashedPassword,
      avatar: 'knight'
    })

  res.status(200).json({ success: true });
  return; // finalize the function
}

export function checkAuthController(req: Request, res: Response, next: NextFunction): void {
  const userObject = req.user;
  if (!userObject) {
    res.json({ message: 'No user logged in' })
    next();
    return; // Stop function execution
  }

  // Send serialized user to the client
  res.status(200).json({ user: userObject });
}

export async function logOutController (req: Request, res: Response, next: NextFunction): Promise<void> {
  if (!req.user) {
    next(new Error(`Occurred an error with user`));
    return;
  }

  const db = await getDb();
  const sessionId = req.sessionID;

  if (!sessionId) {
     next(new Error(`Occurred an error with the session ID`));
     return;
  };

  // Delete the session from the database
  await db.collection('sessions').deleteOne({ _id: sessionId as any })

  // Logging the user out
  req.logout((err) => {
    if (err || !req.user)
      next(err);
    res.status(200).json({ success: true });
  });

  return
}